"""Industry SCS component library seed data."""

COMPONENT_SEED: list[dict] = [
    {
        "type": "sample_probe",
        "label": "取样探头",
        "label_en": "Sample Probe",
        "category": "取样",
        "ports_json": {"in": [], "out": ["sample"]},
        "defaults_json": {
            "insertionDepthMm": 50,
            "material": "316SS",
            "filterGradeUm": 2,
            "doubleBlockBleed": True,
            "holdupVolumeMl": 5,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "insertionDepthMm": {"type": "number", "title": "插入深度 (mm)"},
                "material": {
                    "type": "string",
                    "title": "材质",
                    "enum": ["316SS", "Hastelloy", "PTFE_lined"],
                },
                "filterGradeUm": {"type": "number", "title": "过滤级 (μm)"},
                "doubleBlockBleed": {"type": "boolean", "title": "双重隔离+泄放"},
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
            },
        },
        "engineering_notes_zh": "取样点应靠近工艺代表点；必须配置双重隔离阀(DBB)以降低维护风险；最小化探头内死体积。",
    },
    {
        "type": "sample_line",
        "label": "伴热管线",
        "label_en": "Sample Line",
        "category": "取样",
        "ports_json": {"in": ["in"], "out": ["out"]},
        "defaults_json": {
            "lengthM": 10,
            "odMm": 6,
            "traceHeated": True,
            "tracePowerW": 30,
            "insulation": True,
            "material": "316SS",
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "lengthM": {"type": "number", "title": "长度 (m)"},
                "odMm": {"type": "number", "title": "外径 (mm)"},
                "traceHeated": {"type": "boolean", "title": "电伴热"},
                "tracePowerW": {"type": "number", "title": "伴热功率 (W)"},
                "insulation": {"type": "boolean", "title": "保温"},
                "material": {"type": "string", "title": "材质", "enum": ["316SS", "Hastelloy"]},
            },
        },
        "engineering_notes_zh": "易凝介质必须伴热；伴热温度应高于露点 10–15°C；管线坡度利于排液。",
    },
    {
        "type": "pressure_regulator",
        "label": "减压阀",
        "label_en": "Pressure Regulator",
        "category": "处理",
        "ports_json": {"in": ["in"], "out": ["out"]},
        "defaults_json": {
            "inletBar": 40,
            "outletBar": 2,
            "cv": 0.3,
            "material": "316SS",
            "dPBar": 0.5,
            "holdupVolumeMl": 2,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "inletBar": {"type": "number", "title": "入口压力 (bar)"},
                "outletBar": {"type": "number", "title": "出口设定 (bar)"},
                "cv": {"type": "number", "title": "Cv"},
                "material": {"type": "string", "title": "材质", "enum": ["316SS", "Hastelloy"]},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
            },
        },
        "engineering_notes_zh": "减压级数与压比匹配；出口压力应稳定以满足分析仪要求。",
    },
    {
        "type": "coalescing_filter",
        "label": "凝聚过滤器",
        "label_en": "Coalescing Filter",
        "category": "处理",
        "ports_json": {"in": ["in"], "out": ["out"]},
        "defaults_json": {
            "filterGradeUm": 0.3,
            "holdupVolumeMl": 15,
            "dPBar": 0.2,
            "dPAlarmBar": 0.8,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "filterGradeUm": {"type": "number", "title": "滤芯级 (μm)"},
                "holdupVolumeMl": {"type": "number", "title": "容积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
                "dPAlarmBar": {"type": "number", "title": "堵塞报警 ΔP (bar)"},
            },
        },
        "engineering_notes_zh": "凝聚滤芯用于除雾/油；注意更换周期与旁路隔离。",
    },
    {
        "type": "particulate_filter",
        "label": "颗粒过滤器",
        "label_en": "Particulate Filter",
        "category": "处理",
        "ports_json": {"in": ["in"], "out": ["out"]},
        "defaults_json": {
            "poreSizeUm": 2,
            "changeIntervalDays": 90,
            "holdupVolumeMl": 10,
            "dPBar": 0.15,
            "dPAlarmBar": 0.6,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "poreSizeUm": {"type": "number", "title": "孔径 (μm)"},
                "changeIntervalDays": {"type": "number", "title": "更换周期 (天)"},
                "holdupVolumeMl": {"type": "number", "title": "容积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
                "dPAlarmBar": {"type": "number", "title": "堵塞报警 ΔP (bar)"},
            },
        },
        "engineering_notes_zh": "颗粒过滤保护分析仪阀件；孔径通常 1–7 μm。",
    },
    {
        "type": "knockout_pot",
        "label": "气液分离器",
        "label_en": "Knock-out Pot",
        "category": "处理",
        "ports_json": {"in": ["in"], "out": ["out"], "drain": ["drain"]},
        "defaults_json": {
            "volumeL": 0.5,
            "levelAlarm": True,
            "holdupVolumeMl": 200,
            "dPBar": 0.05,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "volumeL": {"type": "number", "title": "容积 (L)"},
                "levelAlarm": {"type": "boolean", "title": "液位报警"},
                "holdupVolumeMl": {"type": "number", "title": "滞留体积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
            },
        },
        "engineering_notes_zh": "湿气体工况必备；定期排放凝液，防止液击分析仪。",
    },
    {
        "type": "heat_exchanger",
        "label": "冷却器",
        "label_en": "Heat Exchanger / Cooler",
        "category": "处理",
        "ports_json": {"in": ["in"], "out": ["out"]},
        "defaults_json": {
            "targetTempC": 35,
            "dutyKW": 0.5,
            "holdupVolumeMl": 20,
            "dPBar": 0.1,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "targetTempC": {"type": "number", "title": "目标温度 (°C)"},
                "dutyKW": {"type": "number", "title": "换热负荷 (kW)"},
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
            },
        },
        "engineering_notes_zh": "高温样品需冷却至分析仪允许范围；注意结露与腐蚀。",
    },
    {
        "type": "flow_meter",
        "label": "流量计",
        "label_en": "Flow Meter",
        "category": "测量",
        "ports_json": {"in": ["in"], "out": ["out"]},
        "defaults_json": {
            "rangeLph": 10,
            "outputSignal": "4-20mA",
            "holdupVolumeMl": 3,
            "dPBar": 0.05,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "rangeLph": {"type": "number", "title": "量程 (L/h)"},
                "outputSignal": {"type": "string", "title": "输出信号"},
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
            },
        },
        "engineering_notes_zh": "流量测量用于校验旁路与分析仪取样流量一致性。",
    },
    {
        "type": "needle_valve",
        "label": "针阀",
        "label_en": "Needle Valve",
        "category": "测量",
        "ports_json": {"in": ["in"], "out": ["out"]},
        "defaults_json": {
            "setpointLph": 2,
            "controlMode": "manual",
            "holdupVolumeMl": 1,
            "dPBar": 0.2,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "setpointLph": {"type": "number", "title": "设定流量 (L/h)"},
                "controlMode": {
                    "type": "string",
                    "title": "控制模式",
                    "enum": ["manual", "auto"],
                },
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
            },
        },
        "engineering_notes_zh": "针阀用于精细流量调节；与流量计配合整定。",
    },
    {
        "type": "mfc",
        "label": "质量流量控制器",
        "label_en": "MFC",
        "category": "测量",
        "ports_json": {"in": ["in"], "out": ["out"]},
        "defaults_json": {
            "setpointLph": 2,
            "controlMode": "auto",
            "maxFlowLph": 5,
            "holdupVolumeMl": 2,
            "dPBar": 0.3,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "setpointLph": {"type": "number", "title": "设定流量 (L/h)"},
                "controlMode": {"type": "string", "title": "控制模式", "enum": ["manual", "auto"]},
                "maxFlowLph": {"type": "number", "title": "最大流量 (L/h)"},
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
            },
        },
        "engineering_notes_zh": "MFC 提供闭环流量控制，适用于标定与稳定取样。",
    },
    {
        "type": "auto_switch_valve",
        "label": "自动切换阀",
        "label_en": "Auto Switch Valve",
        "category": "切换",
        "ports_json": {"in": ["in"], "out": ["out1", "out2"]},
        "defaults_json": {
            "channels": 2,
            "switchLogic": "time",
            "holdupVolumeMl": 5,
            "dPBar": 0.1,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "channels": {"type": "integer", "title": "通道数"},
                "switchLogic": {
                    "type": "string",
                    "title": "切换逻辑",
                    "enum": ["time", "delta", "manual"],
                },
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
            },
        },
        "engineering_notes_zh": "多流路切换需考虑滞留体积与交叉污染；切换阀前应有过滤。",
    },
    {
        "type": "bypass_loop",
        "label": "快速旁路",
        "label_en": "Bypass / Fast Loop",
        "category": "切换",
        "ports_json": {"in": ["in"], "out": ["out"], "bypass": ["bypass"]},
        "defaults_json": {
            "bypassRatio": 10,
            "deadVolumeMl": 50,
            "lengthM": 5,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "bypassRatio": {"type": "number", "title": "旁路比"},
                "deadVolumeMl": {"type": "number", "title": "死体积 (mL)"},
                "lengthM": {"type": "number", "title": "旁路长度 (m)"},
            },
        },
        "engineering_notes_zh": "快速回路缩短响应时间；分析仪支路流量应远小于主旁路。",
    },
    {
        "type": "vent_bpr",
        "label": "放空/背压阀",
        "label_en": "Vent / Back Pressure Regulator",
        "category": "安全",
        "ports_json": {"in": ["in"], "out": ["vent"]},
        "defaults_json": {
            "backPressureBar": 1.5,
            "ventDestination": "flare",
            "holdupVolumeMl": 2,
            "dPBar": 0.05,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "backPressureBar": {"type": "number", "title": "背压设定 (bar)"},
                "ventDestination": {
                    "type": "string",
                    "title": "放空去向",
                    "enum": ["flare", "vent", "closed"],
                },
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
            },
        },
        "engineering_notes_zh": "背压阀稳定分析仪出口压力；放空须符合安全与环保规范。",
    },
    {
        "type": "cal_gas_inlet",
        "label": "标气接入",
        "label_en": "Calibration Gas Inlet",
        "category": "安全",
        "ports_json": {"in": ["cal"], "out": ["out"]},
        "defaults_json": {
            "pressureBar": 2,
            "purgeTimeS": 120,
            "holdupVolumeMl": 5,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "pressureBar": {"type": "number", "title": "标气压力 (bar)"},
                "purgeTimeS": {"type": "number", "title": "吹扫时间 (s)"},
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
            },
        },
        "engineering_notes_zh": "Ex p 吹扫系统需标气路径与联锁；吹扫时间按容积计算。",
    },
    {
        "type": "analyzer_interface",
        "label": "色谱仪接口",
        "label_en": "Analyzer Interface",
        "category": "分析仪",
        "ports_json": {"in": ["in"], "out": ["vent"]},
        "defaults_json": {
            "lagTargetS": 60,
            "purgeVolumeMl": 50,
            "holdupVolumeMl": 10,
            "dPBar": 0.1,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "lagTargetS": {"type": "number", "title": "滞后目标 (s)"},
                "purgeVolumeMl": {"type": "number", "title": "吹扫体积 (mL)"},
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
            },
        },
        "engineering_notes_zh": "接口阀组应靠近分析仪；满足最小死体积与吹扫要求。",
    },
    {
        "type": "three_way_valve",
        "label": "三通阀",
        "label_en": "3-Way Ball Valve",
        "category": "配管",
        "ports_json": {"in": ["in"], "out": ["out_a", "out_b"]},
        "defaults_json": {
            "activeOut": "out_a",
            "holdupVolumeMl": 2,
            "dPBar": 0.05,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "activeOut": {
                    "type": "string",
                    "title": "当前出口",
                    "enum": ["out_a", "out_b"],
                },
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
            },
        },
        "engineering_notes_zh": "一进两出切换阀；运行时选择连通支路，未选中支路在演示中无流动。",
    },
    {
        "type": "three_way_tee",
        "label": "三通接管",
        "label_en": "3-Way Tee Fitting",
        "category": "配管",
        "ports_json": {"in": ["in"], "out": ["out_a", "out_b"]},
        "defaults_json": {
            "holdupVolumeMl": 1,
            "dPBar": 0.02,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
            },
        },
        "engineering_notes_zh": "被动三通，一进两出分流；演示时两路同时有流动。",
    },
    {
        "type": "flow_rate_regulator",
        "label": "流速调节器",
        "label_en": "Flow Rate Regulator",
        "category": "配管",
        "ports_json": {"in": ["in"], "out": ["out"]},
        "defaults_json": {
            "flowPercent": 80,
            "maxFlowLph": 720,
            "holdupVolumeMl": 3,
            "dPBar": 0.08,
        },
        "param_schema_json": {
            "type": "object",
            "properties": {
                "flowPercent": {"type": "number", "title": "开度 (%)", "minimum": 5, "maximum": 100},
                "maxFlowLph": {"type": "number", "title": "满量程 (L/h)"},
                "holdupVolumeMl": {"type": "number", "title": "死体积 (mL)"},
                "dPBar": {"type": "number", "title": "压降 (bar)"},
            },
        },
        "engineering_notes_zh": "运行时调节气体流速；演示中开度越低，下游气泡越少。",
    },
]
